---
- include_tasks: "install_packages.yml"
- include_tasks: "download_pip_script.yml"
- include_tasks: "install_python_pip.yml"
- name: Copy website file template
  template:
    src: index.html.j2
    dest: "{{ project_dir }}/index.html"
        
- name: Create Apache container
  docker_container:
    name: webapp
    image: httpd
    ports:
    - "{{ external_port }}:{{ internal_port }}"
    volumes:
    - "{{ project_dir }}/index.html:/usr/local/apache2/htdocs/index.html"
